# name of author
name: Sidharth Sarangi
# college registeration number
regdno: 2041019150
# github username
github: SidharthSarangi
# set number (1/2/3)
set: 2
# problem statement number (1/2/3/4)
question: 1
# description of the project
description: The project is hosted on Github pages and the link is https://create-react-app.dev/ and the project is made with ReactJS
# credits of project
credits: Google, Github,React,Facebook,Redux
